import numpy as np

matrix = np.arange(1, 21).reshape((4, 5))
print("The matrix with values ranging from 1 to 20: ")
print(matrix)
print()
zeroes_array = np.zeros(10)
print("The zeroes array: ")
print(zeroes_array)
print()
ones_array = np.ones(10)
print("The ones array: ")
print(ones_array)
print()
fives_array = np.ones(10) * 5
print("The fives array: ")
print(fives_array)
print()
even_array = np.arange(10, 51, 2)
print("Even array: ")
print(even_array)
print()
print("A random number netween 0 and 1")
print(np.random.random())
np.savetxt('matrix.txt', matrix)
loaded_matrix = np.loadtxt('matrix.txt')
print("Loaded matrix:")
print()
print(loaded_matrix)